# 添加多个控制器
controllers: {
  base_controller: {
    # 定义为差速轮
    type: diff_controller,
    # 车体坐标系
    base_frame_id: base_link,
    # 两个轮子间距
    base_width: 0.38,
    # 控制频率
    ticks_meter: 4100,
    # PID控制参数
    Kp: 12,
    Kd: 12,
    Ki: 0,
    Ko: 50,
    # 加速度限制
    accel_limit: 1.0
  }
}